### ISSUE TITLE
No longer working on Rack 2.0.0.rc1.

### ISSUE THREAD

**Issue by phyllisstein** [vigetlabs/olive_branch#3]
Hey there! I love this middleware, and was heartbroken to see that it seems to malfunction under Rack 2.0.0.rc1, which is required for Rails 5 RC1. When I `POST` this payload:

```json
{
  "callbackUri": "https://0.ignota.fyi/login/twitter"
}
```

...I get the following error in my Rails log:

```
NoMethodError - undefined method `deep_transform_keys!' for nil:NilClass:
  olive_branch (1.1.0) lib/olive_branch/middleware.rb:12:in `call'
  rack (2.0.0.rc1) lib/rack/etag.rb:25:in `call'
  rack (2.0.0.rc1) lib/rack/conditional_get.rb:38:in `call'
  rack (2.0.0.rc1) lib/rack/head.rb:12:in `call'
  actionpack (5.0.0.rc1) lib/action_dispatch/middleware/callbacks.rb:38:in `block in call'
  activesupport (5.0.0.rc1) lib/active_support/callbacks.rb:97:in `__run_callbacks__'
  activesupport (5.0.0.rc1) lib/active_support/callbacks.rb:750:in `_run_call_callbacks'
  activesupport (5.0.0.rc1) lib/active_support/callbacks.rb:90:in `run_callbacks'
  actionpack (5.0.0.rc1) lib/action_dispatch/middleware/callbacks.rb:36:in `call'
  actionpack (5.0.0.rc1) lib/action_dispatch/middleware/executor.rb:12:in `call'
  actionpack (5.0.0.rc1) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
  rollbar (2.11.3) lib/rollbar/middleware/rails/rollbar.rb:24:in `block in call'
  rollbar (2.11.3) lib/rollbar.rb:728:in `scoped'
  rollbar (2.11.3) lib/rollbar/middleware/rails/rollbar.rb:22:in `call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:84:in `protected_app_call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:79:in `better_errors_call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:57:in `call'
  actionpack (5.0.0.rc1) lib/action_dispatch/middleware/debug_exceptions.rb:49:in `call'
  rollbar (2.11.3) lib/rollbar/middleware/rails/show_exceptions.rb:22:in `call_with_rollbar'
  actionpack (5.0.0.rc1) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
  railties (5.0.0.rc1) lib/rails/rack/logger.rb:36:in `call_app'
  railties (5.0.0.rc1) lib/rails/rack/logger.rb:24:in `block in call'
  activesupport (5.0.0.rc1) lib/active_support/tagged_logging.rb:70:in `block in tagged'
  activesupport (5.0.0.rc1) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (5.0.0.rc1) lib/active_support/tagged_logging.rb:70:in `tagged'
  railties (5.0.0.rc1) lib/rails/rack/logger.rb:24:in `call'
  actionpack (5.0.0.rc1) lib/action_dispatch/middleware/request_id.rb:24:in `call'
  rack (2.0.0.rc1) lib/rack/runtime.rb:22:in `call'
  activesupport (5.0.0.rc1) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  actionpack (5.0.0.rc1) lib/action_dispatch/middleware/executor.rb:12:in `call'
  actionpack (5.0.0.rc1) lib/action_dispatch/middleware/static.rb:136:in `call'
  rack (2.0.0.rc1) lib/rack/sendfile.rb:111:in `call'
  rack-cors (0.4.0) lib/rack/cors.rb:80:in `call'
  railties (5.0.0.rc1) lib/rails/engine.rb:522:in `call'
  rack (2.0.0.rc1) lib/rack/handler/webrick.rb:86:in `service'
  /usr/local/rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/webrick/httpserver.rb:140:in `service'
  /usr/local/rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/webrick/httpserver.rb:96:in `run'
  /usr/local/rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/webrick/server.rb:296:in `block in start_thread'
```

I'm trying to get up to speed on Rack's guts and submit a fix, but would be grateful for any suggestions you have in the meantime. Thanks a bunch!

**Comment by dce** [comment]
Hey @phyllisstein, thanks for filing this. We're depending on pre-parsed params being available as `env["action_dispatch.request.request_parameters"]` -- looks like they must not be in Rails 5. We'll check it out in the next day or two.

**Comment by phyllisstein** [comment]
Thanks, I appreciate it! Not sure it'll be of any use---there's probably a more elegant implementation out there---but I managed to write a bespoke solution for the app I was working on from which you should feel free to crib: <https://github.com/ignota/volmar/blob/master/lib/sally/middleware.rb>.

**Comment by dce** [comment]
This appears to be the culprit, for what it's worth:

**Comment by efatsi** [comment]
hey @phyllisstein, sorry for the delay here, dedicating some time now to get this up to speed though. Looks like that volmar github project is 404ing for me these days. Any chance you could gist the middleware to share?

**Comment by phyllisstein** [comment]
No worries, and sure thing! This is what’s been working for me for a few months now: https://gist.github.com/phyllisstein/5d0adc566fd8ecca8c102dd61891179e. Not sure it’s the best way to handle this, to be honest, but it gets the job done. Would be only too glad if you managed to improve on it :-).

**Comment by mcfiredrill** [comment]
Having the same issue under rails 4 and rack 1.6, seems `env["action_dispatch.request.request_parameters"]` is not available for whatever reason.

**Comment by efatsi** [comment]
@mcfiredrill just ran a test with Rails 4 and Rack 1.6.4. Looks like `env["action_dispatch.request.request_parameters"]` is available for me. Can you gist your Gemfile.lock so I can try to reproduce?

**Comment by ouabing** [comment]
Hi guys, same issue here with rails 5 :(

**Comment by efatsi** [comment]
@ouabing I've just pushed up v1.2.0, should be compatible with Rails 5.

**Comment by RKushnir** [comment]
@efatsi It fails for me on rails 4.2.7.1 and rack 1.6.4(as well as 1.6.5).

When the request body is empty, `ActionDispatch::ParamsParser` doesn't set the `env["action_dispatch.request.request_parameters"]`. See https://github.com/rails/rails/blob/4-2-stable/actionpack/lib/action_dispatch/middleware/params_parser.rb#L34

Tell me if you need any other details to reproduce it. I'll be happy to help, as at the moment it breaks my GET requests.

**Comment by dphaener** [comment]
:+1: This is still an issue for get requests. Rails 5.0.7 and olive_branch 1.2.3

**Comment by dphaener** [comment]
To continue on this thread, I've found other strange situations that break this.

`GET /myurl?items[]=fooBar` <- causes the same exception
`GET /myurl?items[]=foo_bar` <- also causes an exception IF the param isn't handled in the controller in some way. 

I'm going to attempt a fix for this if I have time in the next couple days.
